---
- name:
  hosts: all
  become: true
  remote_user: root
  tasks:
  - name: collect facts of nodes
    copy:
     dest: /root/hostinfo.txt
     content: "{{ansible_hostname}} {{ansible_processor_count}} {{ansible_default_ipv4.address}} {{ansible_default_ipv4.macaddress}}"

